# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        files: "my_fastapi_app/.*|^tests/.*"
    -   id: end-of-file-fixer
        files: "my_fastapi_app/.*|^tests/.*"
    -   id: check-yaml
        files: "my_fastapi_app/.*|^tests/.*"
    -   id: check-added-large-files
        files: "my_fastapi_app/.*|^tests/.*"
